repos:
  # General code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, ts, jsx, tsx, json, yaml, markdown, css]

  # Conventional commit linting
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  # TypeScript/JavaScript formatting and linting
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bun run lint
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: typescript-check
        name: TypeScript check
        entry: bun run build
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false
